// TODO: Set this to 12
export const MINIMUM_PASSWORD_LENGTH = 2;
export const MILLISECONDS_PER_MINUTE = 60 * 1000;
export const DEFAULT_AUTO_LOCK_TIMEOUT = 10 * MILLISECONDS_PER_MINUTE; // 10 minutes
